#!/usr/bin/with-contenv bash

sed -i 's/this.passwordField.focus(true,300)/this.onLogin()/g' /usr/lib/python2.7/site-packages/deluge/ui/web/js/deluge-all.js
sed -i '203,204 {s/^/#/}' /usr/lib/python2.7/site-packages/deluge/ui/web/auth.py
sed -i '205i\            return True' /usr/lib/python2.7/site-packages/deluge/ui/web/auth.py

# permissions
chown -R abc:abc \
	/config
chown abc:abc \
	/downloads
